### PR TITLE
Removal of the duplicate GScr_getUnixTime function

### PR DESCRIPTION
**Pull request by PrawyCoD1**
Also contains a bit of formatting

### CODE REVIEW

**Comment by kungfooman** [comment]
image

These formatting issues go away when using spaces (I settled on 2 spaces)

**Comment by patriksh** [comment]
Wouldn't be bad to run the whole project through a linter then, but that should be it's own PR.

**Comment by raphael12333** [comment]
@riicchhaarrd hi are you still accepting pull requests on this repo?

**Comment by ghost** [comment]
in this pr it seems it is the `seconds` function that is removed and not `getUnixTime`
Since miscmod now uses the original `seconds` function and removed `getUnixTime` usage, please don't remove `seconds`

**Comment by PrawyCoD1** [comment]
@raphael12333 where are yooou are u alive

**Comment by ghost** [comment]
> @raphael12333 where are yooou are u alive

hii i did put my email address on my github profile feel free to send me a msg it would be a pleasure to stay in touch with you this way while i'm not on discord

**Pull request closed without merging**
